name: Antonio Lennert
favicon: null
layout_spectrum: 0
typography_spectrum: 0.03274455782957375
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.13828302058391273
  lightness: 0.10990761988796294
  saturation: 0.42324768332764506
  rhythmicContrast: 0.9218018229585141
purpose: []
